# Generated by Django 5.1.2 on 2024-11-08 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='phase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_user.phase'),
        ),
        migrations.AlterField(
            model_name='company',
            name='building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vms_user.building'),
        ),
        migrations.DeleteModel(
            name='Visitor',
        ),
    ]
