# Generated by Django 5.1.2 on 2024-11-08 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vms_user', '0002_alter_building_phase_alter_company_building_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('place', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='visitor_photos/')),
                ('visit_time', models.TimeField()),
                ('purpose', models.CharField(choices=[('Business', 'Business'), ('Tourism', 'Tourism'), ('Work', 'Work'), ('Other', 'Other')], max_length=20)),
                ('visit_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=10)),
            ],
        ),
    ]
